<?php
/*
 * CONNECTHUB GLOBAL ANIMATED BACKGROUND
 * Converted from the uploaded Claude HTML banner.
 * Include this file immediately after <body> in header.php.
 */
?>

<style>
/* ============================================================
   CONNECTHUB GLOBAL BACKGROUND
   Works behind every ConnectHub page.
============================================================ */

:root{
    --ch-bg-0:#060814;
    --ch-bg-1:#0b1024;
    --ch-cyan:#3FE0F0;
    --ch-violet:#8B6BFF;
    --ch-magenta:#FF3D9A;
    --ch-gold:#F7C25E;
}

/* Never block buttons, links, forms or games. */
#ch-global-banner,
#ch-global-banner *{
    pointer-events:none !important;
}

#ch-global-banner{
    position:fixed;
    inset:0;
    z-index:0;
    overflow:hidden;
    isolation:isolate;
    background:
        radial-gradient(ellipse 60% 50% at 20% 18%, rgba(139,107,255,.18), transparent 62%),
        radial-gradient(ellipse 55% 45% at 82% 78%, rgba(63,224,240,.14), transparent 62%),
        radial-gradient(ellipse 70% 60% at 52% 100%, rgba(255,61,154,.08), transparent 66%),
        linear-gradient(180deg, var(--ch-bg-0) 0%, var(--ch-bg-1) 100%);
    opacity:.98;
}

#ch-global-banner .ch-bg-layer{
    position:absolute;
    inset:0;
}

/* Faint circuit grid from the original banner. */
#ch-global-banner .ch-grid{
    background-image:
        linear-gradient(rgba(255,255,255,.028) 1px, transparent 1px),
        linear-gradient(90deg, rgba(255,255,255,.028) 1px, transparent 1px);
    background-size:48px 48px;
    -webkit-mask-image:radial-gradient(ellipse 78% 78% at 50% 50%, #000 40%, transparent 87%);
    mask-image:radial-gradient(ellipse 78% 78% at 50% 50%, #000 40%, transparent 87%);
    opacity:.9;
}

/* Soft moving light clouds. */
#ch-global-banner .ch-orb{
    position:absolute;
    border-radius:50%;
    filter:blur(55px);
    opacity:.28;
    transform:translate3d(0,0,0);
    will-change:transform;
}

#ch-global-banner .ch-orb.one{
    width:34vw;
    height:34vw;
    min-width:260px;
    min-height:260px;
    top:-12vw;
    left:-8vw;
    background:radial-gradient(circle, rgba(139,107,255,.55), transparent 68%);
    animation:chOrbOne 13s ease-in-out infinite alternate;
}

#ch-global-banner .ch-orb.two{
    width:30vw;
    height:30vw;
    min-width:230px;
    min-height:230px;
    right:-8vw;
    bottom:-10vw;
    background:radial-gradient(circle, rgba(63,224,240,.42), transparent 68%);
    animation:chOrbTwo 15s ease-in-out infinite alternate;
}

#ch-global-banner .ch-orb.three{
    width:25vw;
    height:25vw;
    min-width:200px;
    min-height:200px;
    left:36%;
    bottom:-14vw;
    background:radial-gradient(circle, rgba(255,61,154,.30), transparent 70%);
    animation:chOrbThree 17s ease-in-out infinite alternate;
}

@keyframes chOrbOne{
    from{ transform:translate3d(0,0,0) scale(1); }
    to{ transform:translate3d(8vw,5vh,0) scale(1.12); }
}

@keyframes chOrbTwo{
    from{ transform:translate3d(0,0,0) scale(1); }
    to{ transform:translate3d(-7vw,-5vh,0) scale(1.10); }
}

@keyframes chOrbThree{
    from{ transform:translate3d(0,0,0) scale(.96); }
    to{ transform:translate3d(4vw,-7vh,0) scale(1.13); }
}

/* Border/frame from the original banner, adapted as a page frame. */
#ch-global-banner .ch-frame{
    position:absolute;
    inset:18px;
    border:1px solid rgba(255,255,255,.055);
    border-radius:22px;
    box-shadow:
        0 0 80px rgba(139,107,255,.04) inset,
        0 0 70px rgba(63,224,240,.025);
}

/* Thin animated sweep. */
#ch-global-banner .ch-sweep{
    position:absolute;
    top:-20%;
    left:-30%;
    width:22%;
    height:140%;
    transform:rotate(8deg);
    background:linear-gradient(90deg, transparent, rgba(255,255,255,.07), transparent);
    mix-blend-mode:screen;
    filter:blur(2px);
    animation:chSweep 9s ease-in-out infinite;
}

@keyframes chSweep{
    0%, 55%{ left:-30%; opacity:0; }
    64%{ opacity:.9; }
    84%,100%{ left:120%; opacity:0; }
}

/* Sparkles generated by JavaScript. */
#ch-global-banner .ch-sparkle{
    position:absolute;
    border-radius:50%;
    background:#fff;
    box-shadow:
        0 0 8px rgba(255,255,255,.45),
        0 0 18px rgba(139,107,255,.12);
    animation:chTwinkle ease-in-out infinite;
    opacity:0;
}

@keyframes chTwinkle{
    0%,100%{
        opacity:0;
        transform:scale(.35) translateY(0);
    }
    50%{
        opacity:var(--ch-peak,.75);
        transform:scale(1) translateY(-5px);
    }
}

/* Cursor/touch glow follows the user's pointer without blocking UI. */
#ch-global-banner .ch-cursor-glow{
    position:absolute;
    width:230px;
    height:230px;
    margin:-115px 0 0 -115px;
    border-radius:50%;
    background:
        radial-gradient(circle,
            rgba(63,224,240,.10) 0%,
            rgba(139,107,255,.055) 28%,
            rgba(139,107,255,0) 70%);
    filter:blur(5px);
    opacity:0;
    transition:opacity .22s ease;
    will-change:left,top;
}

/* Touch/ripple effect. */
#ch-global-banner .ch-ripple{
    position:absolute;
    width:12px;
    height:12px;
    margin:-6px 0 0 -6px;
    border-radius:50%;
    border:1px solid rgba(63,224,240,.45);
    box-shadow:
        0 0 15px rgba(63,224,240,.25),
        0 0 30px rgba(139,107,255,.12);
    animation:chRipple .75s ease-out forwards;
}

@keyframes chRipple{
    0%{
        opacity:.85;
        transform:scale(.5);
    }
    100%{
        opacity:0;
        transform:scale(14);
    }
}

/* Gentle moving scan line. */
#ch-global-banner .ch-scanline{
    position:absolute;
    left:0;
    right:0;
    height:1px;
    top:-10%;
    background:linear-gradient(90deg, transparent, rgba(63,224,240,.11), transparent);
    box-shadow:0 0 15px rgba(63,224,240,.08);
    animation:chScan 11s linear infinite;
}

@keyframes chScan{
    0%{ top:-10%; opacity:0; }
    8%{ opacity:.7; }
    50%{ opacity:.55; }
    92%{ opacity:.2; }
    100%{ top:110%; opacity:0; }
}

/* Keep normal page content above the background. */
body > .layout,
body > main,
body > header,
body > footer,
body > .container,
body > #app,
body > #root{
    position:relative;
    z-index:1;
}

/* Your fixed sidebar/header remain visually dominant. */
.layout > nav,
.layout > main > header{
    position:relative;
    z-index:5;
}

@media(max-width:800px){
    #ch-global-banner .ch-frame{
        inset:10px;
        border-radius:15px;
    }
    #ch-global-banner .ch-grid{
        background-size:36px 36px;
    }
    #ch-global-banner .ch-cursor-glow{
        width:170px;
        height:170px;
        margin:-85px 0 0 -85px;
    }
}

@media(prefers-reduced-motion:reduce){
    #ch-global-banner .ch-orb,
    #ch-global-banner .ch-sweep,
    #ch-global-banner .ch-scanline,
    #ch-global-banner .ch-sparkle{
        animation:none !important;
    }
}
</style>

<div id="ch-global-banner" aria-hidden="true">
    <div class="ch-bg-layer ch-grid"></div>
    <div class="ch-bg-layer">
        <div class="ch-orb one"></div>
        <div class="ch-orb two"></div>
        <div class="ch-orb three"></div>
    </div>
    <div class="ch-frame"></div>
    <div class="ch-sweep"></div>
    <div class="ch-scanline"></div>
    <div class="ch-cursor-glow" id="chCursorGlow"></div>
</div>

<script>
(function(){
    'use strict';

    const layer = document.getElementById('ch-global-banner');
    if(!layer) return;

    /* ========================================================
       SPARKLES
    ======================================================== */
    const sparkleCount = 90;

    for(let i = 0; i < sparkleCount; i++){
        const s = document.createElement('div');
        s.className = 'ch-sparkle';

        const size = (Math.random() * 2.2 + 0.8).toFixed(2);
        s.style.width = size + 'px';
        s.style.height = size + 'px';
        s.style.left = (Math.random() * 100) + '%';
        s.style.top = (Math.random() * 100) + '%';
        s.style.setProperty(
            '--ch-peak',
            (Math.random() * .60 + .35).toFixed(2)
        );
        s.style.animationDuration =
            (Math.random() * 3 + 2).toFixed(2) + 's';
        s.style.animationDelay =
            (Math.random() * 4).toFixed(2) + 's';

        layer.appendChild(s);
    }

    /* ========================================================
       POINTER GLOW
    ======================================================== */
    const glow = document.getElementById('chCursorGlow');

    let glowVisible = false;

    function moveGlow(clientX, clientY){
        if(!glow) return;

        glow.style.left = clientX + 'px';
        glow.style.top = clientY + 'px';

        if(!glowVisible){
            glowVisible = true;
            glow.style.opacity = '1';
        }
    }

    window.addEventListener(
        'pointermove',
        function(event){
            moveGlow(event.clientX, event.clientY);
        },
        { passive:true }
    );

    /* ========================================================
       TOUCH / CLICK RIPPLE
       It appears behind the page UI.
    ======================================================== */
    let rippleTimer = null;

    function createRipple(clientX, clientY){
        const ripple = document.createElement('div');
        ripple.className = 'ch-ripple';
        ripple.style.left = clientX + 'px';
        ripple.style.top = clientY + 'px';
        layer.appendChild(ripple);

        window.setTimeout(function(){
            ripple.remove();
        }, 800);
    }

    window.addEventListener(
        'pointerdown',
        function(event){
            createRipple(event.clientX, event.clientY);
        },
        { passive:true }
    );

    /* Prevent excessive ripple generation on touchmove. */
    window.addEventListener(
        'pointermove',
        function(event){
            if(event.pointerType !== 'touch') return;
            if(rippleTimer) return;

            rippleTimer = window.setTimeout(function(){
                rippleTimer = null;
            }, 100);
        },
        { passive:true }
    );

})();
</script>
